name: Build and Push to GitHub Container Registry (GHCR)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Convert repository owner to lowercase
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')/invoice:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')/invoice:latest